version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  test:
    docker:
      - image: circleci/node:lts
        environment:
          DB_USER: postgres
      - image: postgres:13-alpine
        environment:
          POSTGRES_DB: nestjs-psf-tests
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: npm test

workflows:
  test:
    jobs:
      - test
